import {cpSync, copyFileSync, mkdirSync, readFileSync, writeFileSync, existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {resolve,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const host=execFileSync('rustc',['-vV'],{encoding:'utf8'}).match(/^host: (.+)$/m)[1];
const version=readFileSync(join(root,'Cargo.toml'),'utf8').match(/^version = "([^"]+)"/m)[1];
const name=`natsui-${version}-${host}`;
const out=join(root,'dist-release'),dir=join(out,name);mkdirSync(dir,{recursive:true});
const binary=process.platform==='win32'?'natsui.exe':'natsui';
if(!existsSync(join(root,'target/release',binary)))throw new Error('Run cargo build --release --locked first.');
const source=join(root,'target/release',binary),destination=join(dir,binary);
const digest=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
if(!existsSync(destination)||digest(source)!==digest(destination))copyFileSync(source,destination);
for(const file of ['README.md','LICENSE','SECURITY.md','RELEASE_CHECKLIST.md','PORTING_LEDGER.md','SETTINGS_AND_ACCESS.md','RESOURCE_METRICS_AND_TRENDS.md','ASSESSMENT.md'])copyFileSync(join(root,file),join(dir,file));
cpSync(join(root,'docs'),join(dir,'docs'),{recursive:true});
mkdirSync(join(dir,'demo'),{recursive:true});copyFileSync(join(root,'demo/README.md'),join(dir,'demo/README.md'));
mkdirSync(join(dir,'deploy'),{recursive:true});copyFileSync(join(root,'deploy/permissions.conf'),join(dir,'deploy/permissions.conf'));
writeFileSync(join(dir,'QUICKSTART.txt'),`Natsui ${version} (${host})\n\nRun ${binary==='natsui.exe'?'.\\natsui.exe':'./natsui'} --demo for the local simulation.\nOpen http://127.0.0.1:4321 in a browser.\n\nFor real data, set NATSUI_URL and NATSUI_PROFILE and run without --demo.\nSee README.md and SECURITY.md for credentials and access boundaries.\nDocker and source-build commands in README.md require a source checkout.\n`);
const archive=join(out,name+'.tar.gz');
execFileSync('tar',['-czf',archive,'-C',out,name]);
writeFileSync(archive+'.sha256',createHash('sha256').update(readFileSync(archive)).digest('hex')+'  '+name+'.tar.gz\n');
console.log(archive);
