import {cpSync, copyFileSync, mkdirSync, readFileSync, writeFileSync, existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {resolve,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const host=execFileSync('rustc',['-vV'],{encoding:'utf8'}).match(/^host: (.+)$/m)[1];
const version=readFileSync(join(root,'Cargo.toml'),'utf8').match(/^version = "([^"]+)"/m)[1];
const name=`natsui-${version}-${host}`;
const out=join(root,'dist-release'),dir=join(out,name);mkdirSync(dir,{recursive:true});
const binary=process.platform==='win32'?'natsui.exe':'natsui';
if(!existsSync(join(root,'target/release',binary)))throw new Error('Run cargo build --release --locked first.');
const source=join(root,'target/release',binary),destination=join(dir,binary);
const digest=file=>createHash('sha256').update(readFileSync(file)).digest('hex');
if(!existsSync(destination)||digest(source)!==digest(destination))copyFileSync(source,destination);
for(const file of ['README.md','LICENSE','SECURITY.md','RELEASE_CHECKLIST.md','PORTING_LEDGER.md','SETTINGS_AND_ACCESS.md','RESOURCE_METRICS_AND_TRENDS.md','ASSESSMENT.md'])copyFileSync(join(root,file),join(dir,file));
cpSync(join(root,'docs'),join(dir,'docs'),{recursive:true});
mkdirSync(join(dir,'demo'),{recursive:true});
for(const file of ['demo/README.md','demo/published.yaml','compose.yaml'])copyFileSync(join(root,file),join(dir,file));
mkdirSync(join(dir,'deploy'),{recursive:true});for(const name of ["permissions.conf","compose.auth.yaml","compose.network.yaml","compose.nats-login.yaml","compose.tls.yaml","compose.mtls.yaml","compose.creds.yaml"])copyFileSync(join(root,'deploy',name),join(dir,'deploy',name));
cpSync(join(root,'deploy/ansible'),join(dir,'deploy/ansible'),{recursive:true});
cpSync(join(root,'controller'),join(dir,'controller'),{recursive:true,filter:source=>!source.includes('__pycache__')});
writeFileSync(join(dir,'QUICKSTART.txt'),`Natsui ${version} (${host})\n\nRun ${binary==='natsui.exe'?'.\\natsui.exe':'./natsui'} --demo for the local simulation.\nOpen http://127.0.0.1:4321 in a browser.\n\nFor real data, set NATSUI_URL and NATSUI_PROFILE and run without --demo.\nSee README.md and SECURITY.md for credentials and access boundaries.\nDocker and source-build commands in README.md require a source checkout.\n`);
const archive=join(out,name+'.tar.gz');
// Relative archive paths avoid GNU tar interpreting Windows drive letters as remote hosts.
execFileSync('tar',['-czf',name+'.tar.gz',name],{cwd:out});
writeFileSync(archive+'.sha256',createHash('sha256').update(readFileSync(archive)).digest('hex')+'  '+name+'.tar.gz\n');
console.log(archive);
