use axum::{
    Json,
    extract::{Request, State},
    http::{HeaderMap, Method, StatusCode, header},
    middleware::Next,
    response::{Html, IntoResponse, Redirect, Response},
};
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::{
    collections::HashMap,
    io::{Read, Write},
    path::Path,
    sync::{Arc, Mutex},
    time::{Duration, Instant},
};
use subtle::ConstantTimeEq;

const SESSION_SECONDS: u64 = 8 * 60 * 60;
const COOKIE: &str = "natsui_session";

#[derive(Clone)]
pub struct Auth(Option<Arc<Protected>>);
struct Protected {
    key: [u8; 32],
    sessions: Mutex<HashMap<[u8; 32], Instant>>,
    attempts: Mutex<(Instant, u32)>,
}
fn digest(value: &str) -> [u8; 32] {
    Sha256::digest(value.as_bytes()).into()
}
fn random_key() -> Result<String, String> {
    let mut bytes = [0u8; 32];
    getrandom::fill(&mut bytes).map_err(|_| "Operating system randomness unavailable")?;
    Ok(bytes.iter().map(|b| format!("{b:02x}")).collect())
}
pub fn initialize(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let key = random_key()?;
    let mut options = std::fs::OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = options.open(path)?;
    writeln!(file, "{key}")?;
    file.sync_all()?;
    Ok(())
}
impl Auth {
    pub fn disabled() -> Self {
        Self(None)
    }
    pub fn enabled(&self) -> bool {
        self.0.is_some()
    }
    pub fn from_env() -> Result<Self, String> {
        match std::env::var("NATSUI_AUTH_TOKEN_FILE") {
            Err(std::env::VarError::NotPresent) => Ok(Self::disabled()),
            Err(_) => Err("NATSUI_AUTH_TOKEN_FILE must be a valid path".into()),
            Ok(path) => Self::from_file(Path::new(&path)),
        }
    }
    pub fn from_file(path: &Path) -> Result<Self, String> {
        let mut value = String::new();
        std::fs::File::open(path)
            .and_then(|f| f.take(513).read_to_string(&mut value))
            .map_err(|_| "Dashboard access key file could not be read")?;
        if value.len() > 512 {
            return Err("Invalid dashboard access key file".into());
        }
        Self::from_key(value.trim())
    }
    fn from_key(value: &str) -> Result<Self, String> {
        if value.len() != 64 || !value.bytes().all(|b| b.is_ascii_hexdigit()) {
            return Err(
                "Dashboard access key must be 64 hexadecimal characters generated by --init-auth"
                    .into(),
            );
        }
        Ok(Self(Some(Arc::new(Protected {
            key: digest(value),
            sessions: Mutex::new(HashMap::new()),
            attempts: Mutex::new((Instant::now(), 0)),
        }))))
    }
    fn issue(&self, key: &str, old: Option<&str>) -> Result<String, StatusCode> {
        let protected = self.0.as_ref().ok_or(StatusCode::NOT_FOUND)?;
        let now = Instant::now();
        {
            let mut attempts = protected
                .attempts
                .lock()
                .map_err(|_| StatusCode::SERVICE_UNAVAILABLE)?;
            if now.duration_since(attempts.0) >= Duration::from_secs(60) {
                *attempts = (now, 0);
            }
            if attempts.1 >= 30 {
                return Err(StatusCode::TOO_MANY_REQUESTS);
            }
            attempts.1 += 1;
        }
        if key.len() != 64 || !bool::from(protected.key.ct_eq(&digest(key))) {
            return Err(StatusCode::UNAUTHORIZED);
        }
        let token = random_key().map_err(|_| StatusCode::SERVICE_UNAVAILABLE)?;
        let mut sessions = protected
            .sessions
            .lock()
            .map_err(|_| StatusCode::SERVICE_UNAVAILABLE)?;
        sessions.retain(|_, expires| *expires > now);
        if let Some(old) = old {
            sessions.remove(&digest(old));
        }
        if sessions.len() >= 32
            && let Some(oldest) = sessions
                .iter()
                .min_by_key(|(_, expires)| *expires)
                .map(|(key, _)| *key)
        {
            sessions.remove(&oldest);
        }
        sessions.insert(digest(&token), now + Duration::from_secs(SESSION_SECONDS));
        Ok(token)
    }
    fn valid(&self, token: Option<&str>) -> bool {
        let Some(protected) = &self.0 else {
            return true;
        };
        let Some(token) = token.filter(|t| t.len() == 64) else {
            return false;
        };
        let Ok(mut sessions) = protected.sessions.lock() else {
            return false;
        };
        sessions.retain(|_, expires| *expires > Instant::now());
        sessions.contains_key(&digest(token))
    }
    fn revoke(&self, token: Option<&str>) -> Result<(), StatusCode> {
        if let (Some(protected), Some(token)) = (&self.0, token) {
            protected
                .sessions
                .lock()
                .map_err(|_| StatusCode::SERVICE_UNAVAILABLE)?
                .remove(&digest(token));
        }
        Ok(())
    }
}
fn session(headers: &HeaderMap) -> Option<&str> {
    headers
        .get(header::COOKIE)?
        .to_str()
        .ok()?
        .split(';')
        .filter_map(|part| part.trim().split_once('='))
        .find_map(|(name, value)| (name == COOKIE).then_some(value))
}
fn cookie(token: &str, age: u64) -> String {
    // HTTP is restricted to loopback. Public HTTPS/proxy deployment is a separate mode.
    format!("{COOKIE}={token}; Path=/; HttpOnly; SameSite=Strict; Max-Age={age}")
}
pub async fn guard(State(auth): State<Auth>, request: Request, next: Next) -> Response {
    if !auth.enabled() {
        return next.run(request).await;
    }
    if request.method() != Method::GET
        && request.method() != Method::HEAD
        && request
            .headers()
            .get("x-natsui-request")
            .and_then(|h| h.to_str().ok())
            != Some("1")
    {
        return StatusCode::FORBIDDEN.into_response();
    }
    let path = request.uri().path();
    let public = matches!(
        path,
        "/login"
            | "/login.js"
            | "/style.css"
            | "/fibril.css"
            | "/kitten.svg"
            | "/api/auth/login"
            | "/healthz"
            | "/readyz"
    );
    if !public && !auth.valid(session(request.headers())) {
        return if path == "/" {
            Redirect::to("/login").into_response()
        } else {
            StatusCode::UNAUTHORIZED.into_response()
        };
    }
    next.run(request).await
}
pub async fn page(State(app): State<crate::App>, headers: HeaderMap) -> Response {
    if !app.auth.enabled() || app.auth.valid(session(&headers)) {
        return Redirect::to("/").into_response();
    }
    Html(include_str!("../web/login.html")).into_response()
}
#[derive(Deserialize)]
pub struct Credentials {
    key: String,
}
pub async fn login(
    State(app): State<crate::App>,
    headers: HeaderMap,
    Json(credentials): Json<Credentials>,
) -> Response {
    match app.auth.issue(&credentials.key, session(&headers)) {
        Ok(token) => (
            [(header::SET_COOKIE, cookie(&token, SESSION_SECONDS))],
            StatusCode::NO_CONTENT,
        )
            .into_response(),
        Err(status) => {
            let mut response = status.into_response();
            if status == StatusCode::TOO_MANY_REQUESTS {
                response
                    .headers_mut()
                    .insert(header::RETRY_AFTER, "60".parse().unwrap());
            }
            response
        }
    }
}
pub async fn logout(State(app): State<crate::App>, headers: HeaderMap) -> Response {
    match app.auth.revoke(session(&headers)) {
        Ok(()) => (
            [(header::SET_COOKIE, cookie("", 0))],
            StatusCode::NO_CONTENT,
        )
            .into_response(),
        Err(status) => status.into_response(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::{Router, body::Body, routing::get};
    use tower::ServiceExt;
    const KEY: &str = "abababababababababababababababababababababababababababababababab";
    #[test]
    fn session_expiry_revocation_rotation_and_limits() {
        let auth = Auth::from_key(KEY).unwrap();
        assert!(!auth.valid(None));
        assert_eq!(
            auth.issue(&"0".repeat(64), None),
            Err(StatusCode::UNAUTHORIZED)
        );
        let first = auth.issue(KEY, None).unwrap();
        assert!(auth.valid(Some(&first)));
        let second = auth.issue(KEY, Some(&first)).unwrap();
        assert!(!auth.valid(Some(&first)));
        assert!(auth.valid(Some(&second)));
        auth.revoke(Some(&second)).unwrap();
        assert!(!auth.valid(Some(&second)));
        let third = auth.issue(KEY, None).unwrap();
        auth.0
            .as_ref()
            .unwrap()
            .sessions
            .lock()
            .unwrap()
            .insert(digest(&third), Instant::now() - Duration::from_secs(1));
        assert!(!auth.valid(Some(&third)));
        assert!(!Auth::from_key(KEY).unwrap().valid(Some(&first)));
        for _ in 0..30 {
            let _ = auth.issue("wrong", None);
        }
        assert_eq!(auth.issue(KEY, None), Err(StatusCode::TOO_MANY_REQUESTS));
        let c = cookie(&first, SESSION_SECONDS);
        for flag in ["HttpOnly", "SameSite=Strict", "Path=/", "Max-Age=28800"] {
            assert!(c.contains(flag));
        }
    }
    #[test]
    fn sessions_are_bounded_and_rate_limit_recovers() {
        let auth = Auth::from_key(KEY).unwrap();
        let first = auth.issue(KEY, None).unwrap();
        for _ in 0..40 {
            *auth.0.as_ref().unwrap().attempts.lock().unwrap() =
                (Instant::now() - Duration::from_secs(61), 30);
            auth.issue(KEY, None).unwrap();
        }
        assert_eq!(auth.0.as_ref().unwrap().sessions.lock().unwrap().len(), 32);
        assert!(!auth.valid(Some(&first)));
    }
    #[test]
    fn key_files_fail_closed_and_initialization_never_overwrites() {
        let path = std::env::temp_dir().join(format!("natsui-auth-{}", random_key().unwrap()));
        assert!(Auth::from_file(&path).is_err());
        initialize(&path).unwrap();
        assert!(Auth::from_file(&path).unwrap().enabled());
        assert!(initialize(&path).is_err());
        for value in ["", "password", &"0".repeat(513)] {
            std::fs::write(&path, value).unwrap();
            assert!(Auth::from_file(&path).is_err());
        }
        std::fs::remove_file(path).unwrap();
    }
    #[tokio::test]
    async fn guard_protects_reads_writes_assets_and_unknown_routes() {
        let auth = Auth::from_key(KEY).unwrap();
        let token = auth.issue(KEY, None).unwrap();
        let app = Router::new()
            .route("/", get(|| async { "private" }))
            .fallback(|| async { "private" })
            .layer(axum::middleware::from_fn_with_state(auth, guard))
            .layer(axum::middleware::from_fn(crate::local_request));
        for (path, method, credential, origin, request_header, expected) in [
            (
                "/",
                "GET",
                false,
                "http://localhost:4321",
                false,
                StatusCode::SEE_OTHER,
            ),
            (
                "/api/snapshot",
                "GET",
                false,
                "http://localhost:4321",
                false,
                StatusCode::UNAUTHORIZED,
            ),
            (
                "/api/messages/ORDERS/1",
                "GET",
                false,
                "http://localhost:4321",
                false,
                StatusCode::UNAUTHORIZED,
            ),
            (
                "/app.js",
                "GET",
                false,
                "http://localhost:4321",
                false,
                StatusCode::UNAUTHORIZED,
            ),
            (
                "/unknown",
                "GET",
                false,
                "http://localhost:4321",
                false,
                StatusCode::UNAUTHORIZED,
            ),
            (
                "/api/config/apply",
                "POST",
                false,
                "http://localhost:4321",
                true,
                StatusCode::UNAUTHORIZED,
            ),
            (
                "/api/auth/login",
                "POST",
                false,
                "http://localhost:4321",
                false,
                StatusCode::FORBIDDEN,
            ),
            (
                "/api/auth/login",
                "POST",
                false,
                "http://evil.example",
                true,
                StatusCode::FORBIDDEN,
            ),
            (
                "/api/settings",
                "PUT",
                true,
                "http://localhost:4321",
                false,
                StatusCode::FORBIDDEN,
            ),
            (
                "/api/settings",
                "PUT",
                true,
                "http://localhost:4321",
                true,
                StatusCode::OK,
            ),
            (
                "/api/snapshot",
                "GET",
                true,
                "http://localhost:4321",
                false,
                StatusCode::OK,
            ),
            (
                "/login",
                "GET",
                false,
                "http://localhost:4321",
                false,
                StatusCode::OK,
            ),
            (
                "/healthz",
                "GET",
                false,
                "http://localhost:4321",
                false,
                StatusCode::OK,
            ),
            (
                "/readyz",
                "GET",
                false,
                "http://localhost:4321",
                false,
                StatusCode::OK,
            ),
        ] {
            let mut req = axum::http::Request::builder()
                .uri(path)
                .method(method)
                .header("host", "localhost:4321")
                .header("origin", origin);
            if credential {
                req = req.header("cookie", format!("{COOKIE}={token}"));
            }
            if request_header {
                req = req.header("x-natsui-request", "1");
            }
            let response = app
                .clone()
                .oneshot(req.body(Body::empty()).unwrap())
                .await
                .unwrap();
            assert_eq!(response.status(), expected, "{method} {path}");
        }
    }
    #[tokio::test]
    async fn real_login_logout_cookie_and_body_limit() {
        use tokio::sync::RwLock;
        let dir = std::env::temp_dir().join(format!("natsui-login-{}", random_key().unwrap()));
        let auth = Auth::from_key(KEY).unwrap();
        let app = crate::App {
            auth: auth.clone(),
            editor: crate::editing::Editor::new(false),
            db: crate::store::Database::open(dir.to_str().unwrap()).unwrap(),
            current: Arc::new(RwLock::new(crate::simulation::snapshot("auth-test", 0))),
            nats: Arc::new(RwLock::new(None)),
            monitor: crate::monitoring::Monitor::new("").unwrap(),
            demo: true,
            prefix: "$JS.API".into(),
            scope: "auth-test".into(),
            connection: None,
            settings_cache: Arc::new(RwLock::new(crate::store::Settings::default())),
        };
        let router = crate::router(app);
        let request = |path: &str, method: &str, body: String, cookie: Option<&str>| {
            let mut builder = axum::http::Request::builder()
                .uri(path)
                .method(method)
                .header("host", "localhost:4321")
                .header("origin", "http://localhost:4321")
                .header("x-natsui-request", "1")
                .header("content-type", "application/json");
            if let Some(c) = cookie {
                builder = builder.header("cookie", c);
            }
            builder.body(Body::from(body)).unwrap()
        };
        let oversized = router
            .clone()
            .oneshot(request(
                "/api/auth/login",
                "POST",
                serde_json::json!({"key":"a".repeat(2000)}).to_string(),
                None,
            ))
            .await
            .unwrap();
        assert_eq!(oversized.status(), StatusCode::PAYLOAD_TOO_LARGE);
        let invalid = router
            .clone()
            .oneshot(request(
                "/api/auth/login",
                "POST",
                serde_json::json!({"key":"wrong"}).to_string(),
                None,
            ))
            .await
            .unwrap();
        assert_eq!(invalid.status(), StatusCode::UNAUTHORIZED);
        let login = router
            .clone()
            .oneshot(request(
                "/api/auth/login",
                "POST",
                serde_json::json!({"key":KEY}).to_string(),
                None,
            ))
            .await
            .unwrap();
        assert_eq!(login.status(), StatusCode::NO_CONTENT);
        assert!(login.headers().contains_key("content-security-policy"));
        assert_eq!(login.headers()[header::CACHE_CONTROL], "no-store");
        let cookie = login.headers()[header::SET_COOKIE]
            .to_str()
            .unwrap()
            .split(';')
            .next()
            .unwrap()
            .to_owned();
        assert!(!cookie.contains(KEY));
        let snapshot = router
            .clone()
            .oneshot(request(
                "/api/snapshot",
                "GET",
                String::new(),
                Some(&cookie),
            ))
            .await
            .unwrap();
        assert_eq!(snapshot.status(), StatusCode::OK);
        let bytes = axum::body::to_bytes(snapshot.into_body(), 1_000_000)
            .await
            .unwrap();
        assert_eq!(
            serde_json::from_slice::<serde_json::Value>(&bytes).unwrap()["dashboard"]["auth_enabled"],
            true
        );
        let logout = router
            .clone()
            .oneshot(request(
                "/api/auth/logout",
                "POST",
                String::new(),
                Some(&cookie),
            ))
            .await
            .unwrap();
        assert_eq!(logout.status(), StatusCode::NO_CONTENT);
        assert!(
            logout.headers()[header::SET_COOKIE]
                .to_str()
                .unwrap()
                .contains("Max-Age=0")
        );
        assert_eq!(
            router
                .clone()
                .oneshot(request(
                    "/api/snapshot",
                    "GET",
                    String::new(),
                    Some(&cookie)
                ))
                .await
                .unwrap()
                .status(),
            StatusCode::UNAUTHORIZED
        );
        assert_eq!(
            router
                .clone()
                .oneshot(request("/healthz", "GET", String::new(), None))
                .await
                .unwrap()
                .status(),
            StatusCode::OK
        );
        drop(router);
        for entry in std::fs::read_dir(&dir).unwrap() {
            std::fs::remove_file(entry.unwrap().path()).unwrap();
        }
        std::fs::remove_dir(dir).unwrap();
    }
}
