/* Investigation views share the dashboard inventory and recorded observations. */
'use strict';
const workspaceState={events:[],eventError:null,connections:null,subscriptions:null,connectionRates:new Map(),loading:{},previousConnections:null};
Object.assign(pages,{investigate:['Investigate','Compare consumer progress, node resources and recorded events at the same time.'],subjects:['Subjects','Configured capture, consumer eligibility and observed subscription interest.'],replicas:['Replica placement','Stream leaders and replication state across nodes.'],connections:['Connections','Client traffic and subscription context across configured nodes.'],consumer:['Consumer detail','Pending delivery, acknowledgment pressure and progress over time.']});
function consumerIdentity(c){return {name:c.name,stream:c.stream_name,created:c.created??null,stream_created:data.snapshot.streams.find(s=>s.config.name===c.stream_name)?.created??null};}
function consumerUrl(c){return '#consumer?'+new URLSearchParams({stream:c.stream_name,name:c.name});}
function renderConsumer(){
 if(currentPage()!=='consumer')return;
 const c=data.snapshot.consumers.find(c=>c.name===filters().get('name')&&c.stream_name===filters().get('stream'));
 if(!c){empty('consumer-summary','Consumer is not in the observed inventory.');$('consumer-charts').replaceChildren();delete $('consumer-charts').dataset.key;return;}
 $('page-title').textContent=c.name;const host=$('consumer-summary'),key=JSON.stringify(consumerIdentity(c)),open=host.dataset.key===key&&host.querySelector('details')?.open;host.dataset.key=key;
 const identity=consumerIdentity(c),points=resourceSeries('consumer',identity,'pending'),direction=NatsuiTrends.direction(points,data.settings.refresh_seconds),slope=direction?.rate??null;
 host.replaceChildren(element('h2',`${c.stream_name} / ${c.name}`));const grid=element('div',null,'detail-grid');for(const [label,value]of [['Pending delivery',number(c.num_pending)],['Awaiting acknowledgment',number(c.num_ack_pending)],['Ack capacity used',percent(c.num_ack_pending,c.config?.max_ack_pending)||'No finite limit reported'],['Backlog direction',slope==null?'Collecting history':Math.abs(slope)<.1?'Approximately steady':`${slope>0?'Growing':'Draining'} ${number(Math.abs(Math.round(slope)))}/s over ${direction.seconds}s`]]){const card=element('div');card.append(element('span',label),element('strong',value));grid.append(card);}host.append(grid,element('p',`Filters: ${NatsuiSubjects.filters(c).join(', ')}. Waiting pull requests: ${number(c.num_waiting)}. These are requests, not a worker count.`));
 const link=element('a','Browse matching retained records');link.href='#messages?'+new URLSearchParams({stream:c.stream_name,subject:NatsuiSubjects.filters(c)[0]});const stream=element('a','Open stream');stream.href='#stream?name='+encodeURIComponent(c.stream_name);const links=element('div',null,'view-links');links.append(link,stream);host.append(links);
 const config=element('details');config.open=!!open;config.append(element('summary','Reported configuration'),element('pre',JSON.stringify(c.config,null,2)));host.append(config);
 resourceCharts('consumer-charts',key,[{field:'pending',label:'Pending delivery',points:resourceSeries('consumer',identity,'pending')},{field:'ack_pending',label:'Awaiting acknowledgment',points:resourceSeries('consumer',identity,'ack_pending'),note:'Outstanding acknowledgments are separate from pending delivery and business completion.'},{field:'redelivered',label:'Currently tracked redelivered messages',points:resourceSeries('consumer',identity,'redelivered'),note:'Current count, not a lifetime redelivery counter.'},{field:'delivered',label:'Delivery attempts / second',points:resourceSeries('consumer',identity,'delivered',true),note:'Consumer sequence progress includes redeliveries. Resets and collection gaps break the rate.'}]);
}
function renderWorkspace(){renderConsumer();renderIncidents();renderSubjects();renderReplicas();renderConnections();renderInvestigation();if(currentPage()==='investigate'&&filters().get('at')&&investigation.route!==location.hash)investigationRoute();}
function acceptIncidents(result){workspaceState.events=result.status==='fulfilled'?result.value.filter(e=>!String(e.detail).endsWith('.api_audit')&&!String(e.detail).endsWith('.nak')):[];workspaceState.eventError=result.status==='rejected'?'Incident storage is unavailable.':null;}
function chartEvents(){if(currentPage()==='investigate')return investigation.events;const p=currentPage(),f=filters();return workspaceState.events.filter(e=>p==='consumer'?e.stream===f.get('stream')&&e.name===f.get('name'):p==='stream'?e.stream===f.get('name'):p==='node'?e.name===data.monitoring?.nodes?.find(n=>n.server_id===f.get('id'))?.server_name:true);}
function resourceEventUrl(e){if(e.resource==='consumer')return '#consumer?'+new URLSearchParams({stream:e.stream,name:e.name,at:e.at});if(e.resource==='stream'&&e.stream)return '#stream?'+new URLSearchParams({name:e.stream,at:e.at});if(e.resource==='node'){const n=data.monitoring?.nodes?.find(n=>n.server_name===e.name);if(n)return '#node?'+new URLSearchParams({id:n.server_id,at:e.at});}return '#investigate?at='+e.at;}
function eventUrl(e){return '#investigate?'+new URLSearchParams({at:e.at,stream:e.stream||'',consumer:e.resource==='consumer'?e.name:'',node:e.resource==='node'?e.name:''});}
function openIncident(e){$('detail-title').textContent=e.kind;const host=$('detail-body');host.replaceChildren(element('p',new Date(e.at*1000).toLocaleString()),element('p',e.detail),element('p',`${e.source||'Recorded'} / ${e.stream||''} ${e.name||''}`));if(e.changes)host.append(element('pre',JSON.stringify(e.changes,null,2)));const a=element('a','Investigate this time');a.href=eventUrl(e);a.onclick=()=>$('detail-dialog').close();host.append(a);const resource=element('a','Open resource');resource.href=resourceEventUrl(e);resource.onclick=()=>$('detail-dialog').close();host.append(element('span',' / '),resource);$('detail-dialog').showModal();}
function renderIncidents(){const q=$('incident-search').value.toLowerCase(),events=workspaceState.events.filter(e=>`${e.kind} ${e.stream||''} ${e.name||''} ${e.detail}`.toLowerCase().includes(q));$('incident-status').textContent=workspaceState.eventError||`${events.length} matching events from the latest 500. Advisory delivery depends on permissions; connection status alone does not verify them.`;const host=$('incident-list');host.replaceChildren(...events.map(e=>{const row=element('div',null,'incident-row'),button=element('button',e.detail,'name-button');button.onclick=()=>openIncident(e);row.append(element('time',new Date(e.at*1000).toLocaleString()),badge(e.kind,/high|pressure|gap/.test(e.kind)?'warn':''),button,element('span',[e.stream,e.name!==e.stream?e.name:''].filter(Boolean).join(' / '),'secondary'));return row;}));if(!events.length)host.append(element('p','No matching recorded events.','empty'));}
$('incident-search').oninput=renderIncidents;
globalThis.NatsuiWorkspace={chartEvents,openIncident};

function resourceLink(label,url){const a=element('a',label,'name-button');a.href=url;return a;}
function renderSubjects(){
 if(currentPage()!=='subjects')return;const subject=$('subject-query').value.trim(),host=$('subject-results');
 if(!subject){host.replaceChildren(element('p','Enter a subject to see configured matches.'));return;}
 if(!NatsuiSubjects.valid(subject)||/[*>]/.test(subject)){host.replaceChildren(element('p','Enter a literal subject, such as orders.created. Wildcards belong in the configured filters.','issue'));return;}
 const streams=data.snapshot.streams.filter(s=>(s.config.subjects||[]).some(f=>NatsuiSubjects.matches(f,subject))),consumers=data.snapshot.consumers.filter(c=>streams.some(s=>s.config.name===c.stream_name)&&NatsuiSubjects.filters(c).some(f=>NatsuiSubjects.matches(f,subject)));
 const panels=element('div',null,'subject-context'),left=element('section'),right=element('section');left.append(element('h3',`${streams.length} configured capturing streams`));
 for(const s of streams){const row=element('p');row.append(resourceLink(s.config.name,'#stream?name='+encodeURIComponent(s.config.name)),element('span',' / '+s.config.subjects.filter(f=>NatsuiSubjects.matches(f,subject)).join(', ')+' / '),resourceLink('Inspect storage','#messages?'+new URLSearchParams({stream:s.config.name,subject})));left.append(row);}
 if(!streams.length)left.append(element('p','No configured capture match in the observed inventory. Mirrors and sources can retain messages without a local capture rule.'));
 right.append(element('h3',`${consumers.length} matching consumers on capturing streams`));for(const c of consumers){const row=element('p');row.append(resourceLink(c.name,consumerUrl(c)),element('span',` / ${c.stream_name} / ${NatsuiSubjects.filters(c).filter(f=>NatsuiSubjects.matches(f,subject)).join(', ')}`));right.append(row);}if(!consumers.length)right.append(element('p','No matching consumer filters observed.'));
 panels.append(left,right);host.replaceChildren(panels,element('p',`Inventory observed ${new Date(data.snapshot.observed_at*1000).toLocaleTimeString()} / ${data.snapshot.status}. Matches do not prove a message was stored or delivered.`,'panel-note'));renderSubscriptions();
}
$('subject-form').onsubmit=e=>{e.preventDefault();filterUrl('q',$('subject-query').value.trim());renderSubjects();};
function inventoryRows(kind){const result=workspaceState[kind];return (result?.nodes||[]).flatMap(n=>(n.rows||[]).map(row=>({...row,node:n})));}
function inventoryStatus(kind){const result=workspaceState[kind];if(!result)return 'No monitoring inventory loaded.';const nodes=result.nodes||[],good=nodes.filter(n=>n.status==='complete');return `${good.length}/${nodes.length} ${result.demo?'simulated nodes':'endpoints returned data'}. Page ${result.page+1}, up to 100 records per endpoint. Search applies to this loaded page. ${result.scope||''}. Observed ${new Date(result.at*1000).toLocaleTimeString()}.`+(nodes.some(n=>n.status!=='complete')?' Some endpoint data is unavailable.':'')+(Date.now()/1000-result.at>30?' Loaded inventory is older than 30 seconds; refresh for current state.':'');}
async function loadInventory(kind,page=0){
 if(workspaceState.loading[kind])return;workspaceState.loading[kind]=true;const button=$(kind==='subscriptions'?'load-subscriptions':'load-workspace-connections');button.disabled=true;$(kind+'-status').textContent='Loading monitoring inventory...';
 try{const result=await api(`/api/monitoring/${kind}?page=${page}`);if(kind==='connections'){workspaceState.previousConnections=workspaceState.connections;workspaceState.connectionRates.clear();const old=(workspaceState.previousConnections?.nodes||[]).flatMap(n=>(n.rows||[]).map(c=>({...c,node:n})));for(const n of result.nodes||[])for(const c of n.rows||[]){const p=old.find(p=>p.cid===c.cid&&p.start===c.start&&p.node.server_id===n.server_id&&p.node.start===n.start);const dt=p?n.at-p.node.at:0;if(p&&c.start&&n.server_id&&dt>0&&dt<=30){const rate=field=>typeof c[field]==='number'&&typeof p[field]==='number'&&c[field]>=p[field]?(c[field]-p[field])/dt:null;workspaceState.connectionRates.set(`${n.slot}/${c.cid}`,{in:rate('in_msgs'),out:rate('out_msgs')});}}}
 workspaceState[kind]=result;$(kind+'-previous').disabled=page===0;$(kind+'-next').disabled=!result.nodes?.some(n=>n.total>(page+1)*100);if(kind==='subscriptions')renderSubscriptions();else renderConnections();
 }catch(error){$(kind+'-status').textContent=error.message+' Previously loaded rows are stale.';workspaceState[kind]=null;$(kind==='subscriptions'?'subscriptions-table':'connections-table').replaceChildren();$(kind+'-next').disabled=true;$(kind+'-previous').disabled=true;}
 finally{workspaceState.loading[kind]=false;button.disabled=false;}
}
function renderSubscriptions(){if(!workspaceState.subscriptions)return;const subject=$('subject-query').value.trim(),rows=inventoryRows('subscriptions').filter(r=>!subject||NatsuiSubjects.matches(r.subject,subject));$('subscriptions-status').textContent=inventoryStatus('subscriptions')+` ${rows.length} matching subscriptions.`;setTable('subscriptions-table',table([['Node'],['Account'],['Subject'],['Queue group'],['Connection'],['Received',true]],rows.map(r=>[cell(r.node.name||`Endpoint ${r.node.slot+1}`),cell(r.account||'Not reported'),cell(r.subject),cell(r.qgroup||'None'),cell(r.cid??'--'),cell(number(r.msgs),true)])));}
$('load-subscriptions').onclick=()=>loadInventory('subscriptions');$('subscriptions-previous').onclick=()=>loadInventory('subscriptions',workspaceState.subscriptions.page-1);$('subscriptions-next').onclick=()=>loadInventory('subscriptions',workspaceState.subscriptions.page+1);
function renderReplicas(){
 if(currentPage()!=='replicas')return;const streams=data.snapshot.streams,nodes=data.monitoring?.nodes||[];
 const names=[...new Set([...nodes.map(n=>n.server_name).filter(Boolean),...streams.flatMap(s=>[s.cluster?.leader,...(s.cluster?.replicas||[]).map(r=>r.name)]).filter(Boolean)])].sort();
 if(!streams.length){empty('replica-matrix','No observed stream placement.');return;}
 const rows=streams.map(s=>{const first=cell();first.append(resourceLink(s.config.name,'#stream?name='+encodeURIComponent(s.config.name)),element('span',`${s.config.num_replicas} configured replicas / ${s.cluster?.name||'cluster not reported'}`,'secondary'));return [first,...names.map(name=>{const td=cell();if(s.cluster?.leader===name)td.append(badge('Leader','good'));else{const peer=s.cluster?.replicas?.find(r=>r.name===name);if(peer){td.append(badge(peer.offline?'Offline':peer.current?'Current':'Behind',peer.offline||!peer.current?'warn':'good'));if(peer.lag!=null)td.append(element('span',`Lag ${number(peer.lag)}`,'secondary'));if(peer.active!=null)td.title=`Time since last peer activity: ${(peer.active/1e9).toFixed(3)} seconds`;}else td.append(element('span','Not reported','secondary'));}return td;})];});
 setTable('replica-matrix',table([['Stream'],...names.map(n=>[n])],rows));
}
function renderConnections(){
 if(currentPage()!=='connections'||!workspaceState.connections)return;const q=$('connections-search').value.toLowerCase(),rows=inventoryRows('connections').filter(c=>`${c.node.name} ${c.name||''} ${c.cid} ${c.lang||''} ${c.version||''} ${(c.subjects||[]).join(' ')}`.toLowerCase().includes(q));$('connections-status').textContent=inventoryStatus('connections')+` ${rows.length} matching clients. Rates need two reads within 30 seconds.`;
 setTable('connections-table',table([['Client'],['Node'],['SDK'],['Inbound /s',true],['Outbound /s',true],['RTT'],['Pending bytes',true],['Subscriptions',true]],rows.map(c=>{const first=cell(),button=element('button',c.name||`Connection ${c.cid}`,'name-button');button.onclick=()=>connectionDetail(c);first.append(button,element('span',`ID ${c.cid}`,'secondary'));const rates=workspaceState.connectionRates.get(`${c.node.slot}/${c.cid}`);return [first,cell(c.node.name||`Endpoint ${c.node.slot+1}`),cell(`${c.lang||'Unknown'} ${c.version||''}`),cell(rates?.in==null?'--':rates.in.toFixed(1),true),cell(rates?.out==null?'--':rates.out.toFixed(1),true),cell(c.rtt||'--'),cell(bytes(c.pending_bytes),true),cell(number(c.subscriptions),true)];})));
}
function connectionDetail(c){$('detail-title').textContent=c.name||`Connection ${c.cid}`;const host=$('detail-body');host.replaceChildren(element('p',`${c.node.name||'Node'} / connection ${c.cid} / ${c.lang||'SDK unknown'} ${c.version||''}`),element('p',`Inbound: ${number(c.in_msgs)} messages / ${bytes(c.in_bytes)}. Outbound: ${number(c.out_msgs)} messages / ${bytes(c.out_bytes)}. Counters are since connection start.`),element('p',`RTT ${c.rtt||'unavailable'} / pending output ${bytes(c.pending_bytes)}`),element('h3','Observed subscriptions'));for(const subject of c.subjects||[]){const row=element('p');if(/[*>]/.test(subject))row.textContent=subject;else {const link=resourceLink(subject,'#subjects?q='+encodeURIComponent(subject));link.onclick=()=>$('detail-dialog').close();row.append(link);}host.append(row);}if(c.subjects_truncated)host.append(element('p','Subscription list truncated to 200 entries.'));if(!c.subjects?.length)host.append(element('p','No subscription subjects returned.'));$('detail-dialog').showModal();}
$('load-workspace-connections').onclick=()=>loadInventory('connections',workspaceState.connections?.page||0);$('connections-search').oninput=renderConnections;$('connections-previous').onclick=()=>loadInventory('connections',workspaceState.connections.page-1);$('connections-next').onclick=()=>loadInventory('connections',workspaceState.connections.page+1);
window.addEventListener('hashchange',()=>{if(currentPage()==='subjects'){$('subject-query').value=filters().get('q')||'';if(data)renderSubjects();}if(currentPage()==='connections'&&!workspaceState.connections)loadInventory('connections');});

const investigation={history:[],events:[],paused:false,range:null,loading:false,error:null,truncated:false,ticket:0};
function localDatetime(at){const date=new Date(at*1000);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,19);}
function choices(select,items,label){const old=select.value;const options=items.map(item=>{const option=element('option',label(item));option.value=JSON.stringify(item);return option;});if(select.innerHTML!==options.map(o=>o.outerHTML).join(''))select.replaceChildren(...options);if([...select.options].some(o=>o.value===old))select.value=old;}
function selected(id){try{return JSON.parse($(id).value);}catch{return null;}}
function renderInvestigation(){
 if(currentPage()!=='investigate'||!data)return;
 if(!investigation.paused&&!investigation.loading){investigation.history=history;investigation.events=workspaceState.events;investigation.range=history.length?{from:history[0].at,to:history.at(-1).at}:null;investigation.error=null;}
 const samples=investigation.history,range=investigation.range;
 $('investigation-pause').textContent=investigation.paused?'Resume live view':'Pause view';$('investigation-export').disabled=!samples.length||investigation.loading;const submit=$('investigation-window').querySelector('button');submit.disabled=investigation.loading;
 if(!samples.length||!range){$('investigation-status').textContent=investigation.error||'No recorded samples in this window.';$('investigation-charts').replaceChildren();$('investigation-events').replaceChildren();return;}
 if(!$('investigation-window').contains(document.activeElement)){$('investigation-from').value=localDatetime(range.from);$('investigation-to').value=localDatetime(range.to);}
 const streams=new Map(),consumers=new Map(),nodes=new Map();for(const sample of samples){for(const s of sample.summary.resources?.streams||[])streams.set(JSON.stringify([s.name,s.created]),{name:s.name,created:s.created});for(const c of sample.summary.resources?.consumers||[])consumers.set(JSON.stringify([c.stream,c.name,c.created,c.stream_created]),{name:c.name,stream:c.stream,created:c.created,stream_created:c.stream_created});for(const n of sample.summary.resources?.monitoring?.nodes||[])if(n.server_id)nodes.set(JSON.stringify([n.server_id,n.start]),{server_id:n.server_id,start:n.start,name:n.server_name});}
 choices($('investigation-stream'),[...streams.values()],s=>s.name);let stream=selected('investigation-stream');choices($('investigation-consumer'),[...consumers.values()].filter(c=>c.stream===stream?.name&&c.stream_created===stream?.created),c=>c.name);choices($('investigation-node'),[...nodes.values()],n=>n.name||n.server_id);
 const consumer=selected('investigation-consumer'),node=selected('investigation-node'),interval=data.settings.refresh_seconds;const series=(kind,id,field)=>id?NatsuiTrends.series(samples,kind,id,field,interval):[];
 const charts=[{field:'pending',label:consumer?`${consumer.name} / pending delivery`:'Consumer pending delivery',points:series('consumer',consumer,'pending')},{field:'ack_pending',label:consumer?`${consumer.name} / awaiting acknowledgment`:'Consumer acknowledgments',points:series('consumer',consumer,'ack_pending')},{field:'cpu',label:node?`${node.name} / process CPU`:'Process CPU',points:series('node',node,'cpu'),readout:v=>v.toFixed(1)+'%'},{field:'mem',label:node?`${node.name} / resident RAM`:'Resident RAM',points:series('node',node,'mem'),readout:bytes},{field:'messages',label:stream?`${stream.name} / retained records`:'Retained records',points:series('stream',stream,'messages')},{field:'bytes',label:stream?`${stream.name} / stored bytes`:'Stored bytes',points:series('stream',stream,'bytes'),readout:bytes}];
 const host=$('investigation-charts'),key=JSON.stringify([stream,consumer,node]);if(host.dataset.key!==key||!host.children.length){host.dataset.key=key;host.replaceChildren(...charts.map(c=>{const panel=element('section',null,'panel'),heading=element('div',null,'panel-heading');heading.append(element('h2',c.label));const plot=element('div',null,'chart');plot.dataset.metric=c.field;panel.append(heading,plot);return panel;}));}
 charts.forEach(c=>NatsuiTrends.draw(host.querySelector(`[data-metric="${c.field}"]`),c.points,{label:c.label,format:c.readout||shortNumber,readout:c.readout,group:'investigation',domain:range,interval}));
 const events=investigation.events.filter(e=>e.at>=range.from&&e.at<=range.to),eventHost=$('investigation-events');eventHost.replaceChildren(...events.map(e=>{const button=element('button',`${new Date(e.at*1000).toLocaleTimeString()} / ${e.name||e.stream||e.kind}: ${e.detail}`,'timeline-event quiet');button.onclick=()=>openIncident(e);return button;}));if(!events.length)eventHost.append(element('p','No recorded events in this window. Missing events are not proof that nothing happened.'));
 $('investigation-status').textContent=investigation.loading?'Loading requested window. Previously displayed observations remain below.':investigation.error||`${investigation.paused?'Paused':'Live'} / ${samples.length} samples / ${new Date(range.from*1000).toLocaleString()} to ${new Date(range.to*1000).toLocaleString()}.`+(investigation.truncated?' Sample cap reached: only the latest 240 samples in the requested window are shown. Narrow the range for earlier detail.':'')+(workspaceState.eventError?' Incident storage unavailable.':'');
}
async function loadWindow(from,to){
 if(!Number.isFinite(from)||!Number.isFinite(to)||from>=to||to-from>21600){$('investigation-status').textContent='Choose an increasing time window of at most six hours.';return;}
 const ticket=++investigation.ticket;investigation.paused=true;investigation.loading=true;investigation.error=null;$('investigation-status').textContent='Loading recorded observations...';
 try{const query=new URLSearchParams({from,to});const [result,events]=await Promise.all([api('/api/history/window?'+query),api('/api/incidents?'+query)]);if(ticket!==investigation.ticket)return;investigation.history=result.samples;investigation.range={from,to};investigation.truncated=result.truncated;investigation.events=events;}
 catch(error){if(ticket===investigation.ticket){investigation.history=[];investigation.error=error.message;}}
 finally{if(ticket===investigation.ticket){investigation.loading=false;renderInvestigation();}}
}
$('investigation-window').onsubmit=e=>{e.preventDefault();loadWindow(Math.floor(new Date($('investigation-from').value).getTime()/1000),Math.floor(new Date($('investigation-to').value).getTime()/1000));};
function resumeInvestigation(){investigation.ticket++;investigation.paused=false;investigation.loading=false;investigation.truncated=false;renderInvestigation();}
$('investigation-live').onclick=resumeInvestigation;$('investigation-pause').onclick=()=>{if(investigation.paused)resumeInvestigation();else{investigation.paused=true;renderInvestigation();}};
for(const id of ['investigation-stream','investigation-consumer','investigation-node'])$(id).onchange=renderInvestigation;
$('investigation-export').onclick=()=>{const report={format:'natsui-investigation-v1',exported_at:new Date().toISOString(),profile:data.snapshot.scope,demo:data.snapshot.demo,range:investigation.range,truncated:investigation.truncated,selection:{stream:selected('investigation-stream'),consumer:selected('investigation-consumer'),node:selected('investigation-node')},samples:investigation.history,events:investigation.events.filter(e=>e.at>=investigation.range.from&&e.at<=investigation.range.to),limitations:['Recorded observations only; gaps are not zero values.','Up to 240 samples and 500 incident records per window.','No message payloads or worker business outcomes.']};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=element('a');a.href=url;a.download='natsui-investigation-'+new Date().toISOString().replaceAll(':','-')+'.json';a.click();$('investigation-status').textContent=`Snapshot download requested: ${report.samples.length} samples and ${report.events.length} events. The paused or live view remains available.`;setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function investigationRoute(){if(currentPage()!=='investigate')return;investigation.route=location.hash;const at=Number(filters().get('at'));if(at>0){await loadWindow(Math.max(0,at-120),at+120);const choose=(id,test)=>{const option=[...$(id).options].find(o=>test(JSON.parse(o.value)));if(option)$(id).value=option.value;};choose('investigation-stream',s=>s.name===filters().get('stream'));renderInvestigation();choose('investigation-consumer',c=>c.name===filters().get('consumer'));choose('investigation-node',n=>n.name===filters().get('node'));renderInvestigation();}}
window.addEventListener('hashchange',investigationRoute);
if(currentPage()==='subjects')$('subject-query').value=filters().get('q')||'';
navigate();refresh();if(currentPage()==='connections')loadInventory('connections');
